# Generated by Django 3.0.8 on 2020-12-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project1App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='web_category',
            field=models.CharField(choices=[('Static WebSite', 'Static Website'), ('Dynamic Website', 'Dynamic Website')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='web_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
