# Generated by Django 3.0.8 on 2020-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project1App', '0009_auto_20201204_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
